# Official framework image. Look for the different tagged releases at:
# /https://hub.docker.com/r/library/node/tags
default:
  image: node:lts

.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809


# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
#services:


stages:
  - test
  - package

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
#cache:
#  paths:
#    - node_modules/

# Use LTS nodejs
test_lts:
  stage: test
  except:
    changes:
      - "*.md"
      - "./**/*.md"
      - "./**/**/*.md"
  before_script:
    apt-get update -qq && apt-get install -y -qq libudev-dev libusb-1.0-0
  script:
    - npm install
    - ./scripts/xkeys-server.js test
  interruptible: true

# Use LATEST nodejs
test_latest:
  image: node:latest
  stage: test
  except:
    changes:
      - "*.md"
      - "./**/*.md"
      - "./**/**/*.md"
  before_script:
    apt-get update -qq && apt-get install -y -qq libudev-dev libusb-1.0-0
  script:
    - npm install
    - ./scripts/xkeys-server.js test
  interruptible: true

# Use LTS nodejs
test_lts:
  stage: test
  except:
    changes:
      - "*.md"
      - "./**/*.md"
      - "./**/**/*.md"
  before_script:
    apt-get update -qq && apt-get install -y -qq libudev-dev libusb-1.0-0
  script:
    - npm install
    - ./scripts/xkeys-server.js test
  interruptible: true

# Use LATEST nodejs
build_deb_lts:
  image: node:lts
  stage: package
  except:
    changes:
      - "*.md"
      - "./**/*.md"
      - "./**/**/*.md"
  before_script:
    apt-get update -qq && apt-get install -y -qq libudev-dev libusb-1.0-0
  script:
    - npm install
    - cd build/deb
    - npx pkg -t node16-linux-x64 --out-path application ../..
  interruptible: true


# Use Windows
# - NodeJS is preinstalled (check version?)
#test_windows:
#  stage: test
#  extends:
#  - .shared_windows_runners
#  except:
#    changes:
#      - "*.md"
#      - "./**/*.md"
#      - "./**/**/*.md"
#  script:
#    - npm install
#    - node .\scripts\xkeys-server.js test
#  interruptible: true
